<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Calculator.svcWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/Calculator.svcWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/Calculator.svcWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://tempuri.org/">
    <import location="Calculator.svc.wsdl" namespace="http://tempuri.org/"/>
    <plnk:partnerLinkType name="ICalculatorLinkType">
        <plnk:role name="ICalculatorRole" portType="ns:ICalculator"/>
    </plnk:partnerLinkType>
</definitions>
